### ISSUE TITLE
Create rrt/path planning slides

### ISSUE THREAD

**Issue by joshhting** [RoboJackets/robocup-training#1]

**Comment by jgkamat** [comment]
To keep it simple, you can write the outline in markdown, and I'll convert it to this format (and make sure that everything fits together). Just make sure to add comments on the sections that should be docs only.

If you want to write it in org, I would reccomend using [this file](https://raw.githubusercontent.com/RoboJackets/robocup-training/master/src/1.org) as a template. I have headlines that are docs only marked with a `:docs:` tag. Overall, org and markdown are very similar, but the link and source code formatting is a bit different (which is why I reccomend just writing it in md, the conversion between them is very easy and automated).

Let me know if you need any help! =)

**Comment by joshhting** [comment]
FYI, there is a physics 2212 test on November 1st, two meetings from now, so I will not be able to present the path planning lesson that day.
